apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-test
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 162411490995.dkr.ecr.ap-south-1.amazonaws.com/python-image:1
          ports: 
            - containerPort: 8080
        - name: nodejs
          image: 162411490995.dkr.ecr.ap-south-1.amazonaws.com/nodejs-image:1
          ports: 
            - containerPort: 3000
